# Generated by Django 5.1.6 on 2025-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_lesson_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(to="courses.tag"),
        ),
    ]
